// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqnehantxqogzpwlzlpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxbmVoYW50eHFvZ3pwd2x6bHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTE2NzEsImV4cCI6MjA3Nzc2NzY3MX0.SNFW406KUoLsTTQB_iJps0r2vF9ydJuI34lPe1Tc-24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});